### ISSUE TITLE
How to obtain the ../mimic_abn/temporal_ids.json file?

### ISSUE THREAD

**Issue by ZardCAI** [wjhou/Recap#2]
I encountered a problem while trying to reproduce this project. How should I obtain the --history ../mimic_abn/temporal_ids.json file?

**Comment by wjhou** [comment]
Hi, 

Thanks for your interest in our work.

The `temporal_ids.json` file contains relations (i.e., progression) between two consecutive images, and can be extracted from the Chest ImaGenome Dataset (https://physionet.org/content/chest-imagenome/1.0.0/), in which you can find the `subject_id` and `object_id`.

I will upload a sample file to indicate the data format later so that you can generate this file yourself.

Best,
Ethan

**Comment by wjhou** [comment]
Hi, 

I've uploaded a sample for the `temporal_ids.json` in `./data/mimic_cxr/temporal_ids.json`. The `subject_id` and `object_id` are directly copied from https://physionet.org/content/chest-imagenome/1.0.0/.

You may create this data yourself, and I will upload my script for processing these data later but it could take some time.

Feel free to reopen the issue if you have further questions.

Best, 
Ethan

**Comment by ZardCAI** [comment]
Thanks for your quick reply!

**Comment by mk-runner** [comment]
Amazing work, can you provide specific instructions on which file "temporal_ids.json" refers to in the "Chest ImaGenome Dataset"? Likewise, "progression labels (i.e., better, stable, worse)" in Section 2.2. Thank you.

**Comment by wjhou** [comment]
Hi, 

Thanks for your attention.

The Chest ImaGenome Dataset is available at https://physionet.org/content/chest-imagenome/1.0.0/. 

Once you downloaded the dataset, you need to unzip the `scene_graph.zip` file in the `silver_dataset`. Here is the structure of the dataset:

```
├── gold_dataset
├── silver_dataset
│   ├── scene_graph
│   │   ├── 10cd06e9-5443fef9-9afbe903-e2ce1eb5-dcff1097_SceneGraph.json
│   │   ├── ......
```

Then, you can read the scene_graph.json in which there is a "relationships" key indicating the relationship between two consecutive images of a region. For example, given a case id `10cd06e9-5443fef9-9afbe903-e2ce1eb5-dcff1097` which is shown on the homepage of Chest ImaGenome, its SceneGraph.json file is named `10cd06e9-5443fef9-9afbe903-e2ce1eb5-dcff1097_SceneGraph.json`. 

Once you open it, pick one relationship in the "relationships" value, then `subject_id` and `object_id` are their ids, and the `predicate` is the region-level progression. Take the above id as an example:
```
'predicate': "['No status change']"
'subject_id': '10cd06e9-5443fef9-9afbe903-e2ce1eb5-dcff1097_left upper lung zone'
'object_id': '4bb710ab-ab7d4781-568bcd6e-5079d3e6-7fdb61b6_left upper lung zone'
```

Remove the `_left upper lung zone` then you can get the image id.

In our case, we merge all predicates as the image-level progression, as indicated in our paper.

I also uploaded a sample of temporal_ids.json for reference (https://github.com/wjhou/Recap/blob/main/data/20240101/mimic_cxr/temporal_ids.json).

Best,
Ethan

**Comment by mk-runner** [comment]
I appreciate your thorough response. I now comprehend.
