### ISSUE TITLE
Some issues with the files "MIMIC-CXR_graphs.json" and "id2tag.csv"

### ISSUE THREAD

**Issue by mk-runner** [wjhou/Recap#3]
```python
radgraph_dir="radgraph/1.0.0/MIMIC-CXR_graphs.json"
chexbert_label="./CheXbert/$dataset/id2tag.csv"
```
Great work! Is this the original file output by RadGraph and CheXbert? At least from the source code, `id2tags.csv` is not. Can you provide an example of the corresponding files? Similar to `temporal_id.json`. I am looking forward to your reply. Thank you.

**Comment by wjhou** [comment]
Hi, 

Thanks for your attention. :)

The `radgraph_dir` is available at https://physionet.org/content/radgraph/1.0.0/. Please download it directly. Once you download the dataset, there is a `MIMIC-CXR_graphs.json` file inside.

Regarding the `chexbert_label`, the format is the same as the one used in ORGan, and you can find the file here: https://github.com/wjhou/ORGan/blob/main/data/iu_xray/id2tag.csv.

Best, 
Ethan

**Comment by mk-runner** [comment]
Thank you very much for your response. I've found the Recap and ICON papers very informative and beneficial.
