### ISSUE TITLE
How do I obtain the "MIMIC-ABN" dataset?

### ISSUE THREAD

**Issue by mk-runner** [wjhou/Recap#4]
Perhaps I lack the necessary access permissions, as my PhysioNet account is associated with **@163.com, not Gmail. In this case, how can I obtain access to the MIMIC-ABN dataset?

Additionally, could you please share the file abn_mimic.json with me? My email address is kangliu422@163.com. Thank you!
![image](https://github.com/wjhou/Recap/assets/29909142/96f652b0-7656-48c8-a451-0768ef870a2b)

**Comment by wjhou** [comment]
Hi, @mk-runner 

If you do not have access to the MIMIC-CXR dataset, then you might not have access to the MIMIC-ABN dataset. You should first obtain the certificate as a prerequisite.

Regarding to the JSON data, I can not share the data to you directly. Please obtain the certificate first and then send me an email.

Best, 
Ethan
